insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(1,"public/votegroup/shunanqikuangshida/photo/zhuqing.jpg","开发科","朱庆","男","33","工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(2,"public/votegroup/shunanqikuangshida/photo/zengzhengrong.jpg","质量安全环保科","曾正荣","男","31","工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(3,"public/votegroup/shunanqikuangshida/photo/yangkun.jpg","新闻中心","杨锟","女","33","政工师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(4,"public/votegroup/shunanqikuangshida/photo/zhangyong.jpg","塔里木油气工程分公司","张勇","男","31","工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(5,"public/votegroup/shunanqikuangshida/photo/luoyuhe.jpg","自贡采气作业区","罗玉合","男",35,"生产技术室主任/工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(6,"public/votegroup/shunanqikuangshida/photo/wangchuanjie.jpg","乐山采气作业区","王川杰","男",34,"生产技术室副主任/工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(7,"public/votegroup/shunanqikuangshida/photo/jiangshengfei.jpg","乐山采气作业区","江胜飞","男",30,"工程师 ","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(8,"public/votegroup/shunanqikuangshida/photo/zengcheng.jpg","安岳采气作业区","曾诚","男",28,"生产技术室副主任/工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(9,"public/votegroup/shunanqikuangshida/photo/zhengchuntiao.jpg","长宁页岩气作业区","郑纯桃","男",31,"生产技术室主任/工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(10,"public/votegroup/shunanqikuangshida/photo/wangmiao.jpg","长宁页岩气作业区","王淼","男",32,"中心站站长 ","采气工/中级");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(11,"public/votegroup/shunanqikuangshida/photo/qiuzongyi.jpg","泸州采气作业区","邱宗毅","男",36,"中心站站长 ","采气工/技师(未聘任)");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(12,"public/votegroup/shunanqikuangshida/photo/wangjunli.jpg","纳溪采气作业区","王俊力","男",28,"助理工程师 ","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(13,"public/votegroup/shunanqikuangshida/photo/zounibo.jpg","合江采气作业区","邹尼波","男",33,"生产技术室主任/工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(14,"public/votegroup/shunanqikuangshida/photo/lijian.jpg","渝西采气作业区","李健","男",28,"助理工程师 ","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(15,"public/votegroup/shunanqikuangshida/photo/lanqikui.jpg","荣县天然气净化厂","兰启奎","男",28,"生产技术室副主任/助理工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(16,"public/votegroup/shunanqikuangshida/photo/tianjing.jpg","安岳油气处理厂","田婧","女",28,"生产技术室主任/助理工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(17,"public/votegroup/shunanqikuangshida/photo/dengfeiyong.jpg","勘探开发研究所","邓飞涌","男",35,"勘探室副主任/工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(18,"public/votegroup/shunanqikuangshida/photo/chenweizhi.jpg","工艺研究所","陈维志","男",35,"生产技术室主任/工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(19,"public/votegroup/shunanqikuangshida/photo/fengkelai.jpg","维修抢险中心","冯柯来","男",35,"生产技术室主任/工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(20,"public/votegroup/shunanqikuangshida/photo/wuyajie.jpg","泸州炭黑厂","邬娅洁","女",39,"生产技术室主任/工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(21,"public/votegroup/shunanqikuangshida/photo/zhaoyingding.jpg","试修作业中心","赵英丁","男",34,"生产技术室主任/工程师","/");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(22,"public/votegroup/shunanqikuangshida/photo/chensiyang.jpg","汽车服务中心","陈锶洋","男",31,"/","驾驶员/中级");
insert into countvoting (id, photoUrl,company,name,sex,age,position,level) values(23,"public/votegroup/shunanqikuangshida/photo/lianglonghua.jpg","消防大队","梁龙华","男",29,"/","消防员/中级");